# Generated by Django 2.1.1 on 2018-10-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippr', '0003_auto_20181015_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='lastest_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
