# Generated by Django 2.1.1 on 2018-10-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippr', '0004_auto_20181015_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='description',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
