# Generated by Django 2.1.1 on 2018-10-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippr', '0006_auto_20181018_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='O', max_length=1),
        ),
    ]
