# Generated by Django 2.1.1 on 2018-10-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippr', '0011_auto_20181024_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'get_latest_by': 'date_created'},
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='user',
        ),
    ]
