# Generated by Django 2.1.1 on 2018-11-06 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippr', '0014_auto_20181104_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='resolved',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved', to='snippr.Commit'),
        ),
    ]
