# Generated by Django 2.1.1 on 2018-11-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippr', '0018_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='code',
            field=models.CharField(max_length=1000),
        ),
    ]
